---
language: ruby
rvm:
  - rbx
env:
  - PACKER_VERSION="0.8.2"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y wget unzip
  - sudo mkdir /opt/packer
  - pushd /opt/packer
  - echo "Downloading packer ${PACKER_VERSION}..."
  - sudo wget --no-verbose https://dl.bintray.com/mitchellh/packer/packer_${PACKER_VERSION}_linux_amd64.zip
  - echo "Installing packer ${PACKER_VERSION}..."
  - sudo unzip packer_${PACKER_VERSION}_linux_amd64.zip
  - sudo rm packer_${PACKER_VERSION}_linux_amd64.zip
  - pushd /usr/bin
  - sudo ln -s /opt/packer/* .
deploy:
  provider: script
  script: packer push -name=garandam/centos66min template.json
